name: Mirror to GitHub

on:
  push:
    branches:
      - main

jobs:
  mirror-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.local"

      - name: Mirror to GitHub (excluding .gitea)
        env:
          # You need to add these secrets in your Gitea Repo Settings > Actions > Secrets
          GITHUB_TOKEN: ${{ secrets.GITHUB_MIRROR_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          TARGET_REPO: "gi4nks/atlas"
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "Error: GITHUB_MIRROR_TOKEN secret is missing."
            exit 1
          fi
          
          if [ -z "$GITHUB_USERNAME" ]; then
             echo "Error: GITHUB_USERNAME secret is missing."
             exit 1
          fi

          echo "Preparing to mirror to GitHub..."

          # Create a temporary branch for the sync
          git checkout -b github-sync

          # Remove the .gitea directory from git tracking
          # The '|| true' ensures the step doesn't fail if the directory is already gone
          git rm -r --cached .gitea || true
          rm -rf .gitea

          # Commit the changes locally
          git commit -m "chore: sync from Gitea (excluding .gitea)" --allow-empty

          # Add the GitHub remote with authentication
          # We use the secret token for authentication
          git remote add github "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$TARGET_REPO.git"

          # Force push to the 'main' branch on GitHub
          # Force push is necessary because the histories might slightly diverge due to the extra commit
          echo "Pushing to GitHub..."
          git push -f github github-sync:main

          echo "Successfully mirrored to GitHub!"
